### ISSUE TITLE
Better error message when using the wrong channel

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-cli#202]
When I use the wrong channel with a service (which is easy to do without #201), I get this error:

```
snet --print-traceback client call 49 0.0000001 34.216.72.29:6201 FindFace '{"file@ImageRGB": "tests/test_images/laos.jpg"}'
Traceback (most recent call last):
  File "/home/joel/.virtualenvs/faces/bin/snet", line 11, in <module>
    load_entry_point('snet-cli', 'console_scripts', 'snet')()
  File "/home/joel/work/snet-cli/snet_cli/__init__.py", line 20, in main
    getattr(args.cmd(conf, args), args.fn)()
  File "/home/joel/work/snet-cli/snet_cli/mpe_client_command.py", line 198, in call_server_statelessly
    current_nonce, current_amount, unspent_amount = self._get_channel_state_statelessly(grpc_channel, self.args.channel_id)
  File "/home/joel/work/snet-cli/snet_cli/mpe_client_command.py", line 163, in _get_channel_state_statelessly
    server     = self._get_channel_state_from_server    (grpc_channel, channel_id)
  File "/home/joel/work/snet-cli/snet_cli/mpe_client_command.py", line 145, in _get_channel_state_from_server
    response = getattr(stub, "GetChannelState")(request)
  File "/home/joel/.virtualenvs/faces/lib/python3.6/site-packages/grpc/_channel.py", line 550, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/joel/.virtualenvs/faces/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "channel storage error"
	debug_error_string = "{"created":"@1549225905.437074666","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"channel storage error","grpc_status":2}"
```

This is not obvious I'm using the wrong channel. But if I look at the server logs I get:

```
time="2019-02-03T20:31:45Z" level=warning msg="Channel received belongs to another group of replicas" configGroupId="..."
```

Which is more clear, but people making service calls will not have this information.

**Comment by astroseger** [comment]
ok... now it is technically impossible (unless you use call-lowlevel, in which case it is desirable to get raw error)... So I propose to close this issue.

**Comment by ferrouswheel** [comment]
Cool, thanks!
