### ISSUE TITLE
Issue while creating a identity using mnemonic

### ISSUE THREAD

**Issue by keshrisohit** [singnet/snet-cli#269]
Getting below error while metadata-init for service , if identity is created using  mnemonic

Traceback (most recent call last):
  File "/home/sohit/cli2/bin/snet", line 10, in <module>
    sys.exit(main())
  File "/home/sohit/cli2/lib/python3.6/site-packages/snet_cli/__init__.py", line 22, in main
    getattr(args.cmd(conf, args), args.fn)()
  File "/home/sohit/cli2/lib/python3.6/site-packages/snet_cli/commands.py", line 115, in __init__
    self.ident = ident or self.get_identity()
  File "/home/sohit/cli2/lib/python3.6/site-packages/snet_cli/commands.py", line 149, in get_identity
    return MnemonicIdentityProvider(self.w3, self.config.get_session_field("mnemonic"), self.get_wallet_index())
  File "/home/sohit/cli2/lib/python3.6/site-packages/snet_cli/identity.py", line 112, in __init__
    Mnemonic("english").to_seed(mnemonic))
  File "/home/sohit/cli2/lib/python3.6/site-packages/pycoin/key/BIP32Node.py", line 44, in from_master_secret
    return class_(chain_code=I64[32:], secret_exponent=from_bytes_32(I64[:32]))
  File "/home/sohit/cli2/lib/python3.6/site-packages/pycoin/key/BIP32Node.py", line 66, in __init__
    secret_exponent=secret_exponent, public_pair=public_pair, is_compressed=True)
  File "/home/sohit/cli2/lib/python3.6/site-packages/pycoin/key/Key.py", line 55, in __init__
    or self._secret_exponent >= self._generator.order():
AttributeError: 'NoneType' object has no attribute 'order'

**Comment by arturgontijo** [comment]
Hi @keshrisohit 
Could you please post more info about this error (like version and steps to reproduce it)?

**Comment by vforvalerio87** [comment]
Fixed by #267 https://github.com/singnet/snet-cli/pull/267

**Comment by vforvalerio87** [comment]
Basically we had all dependencies with versions specified as ">=" and pycoin >= 0.90 breaks our implementation of Identity. I fixed it by hardcoding pycoin's version at 0.80 (and hardcoding a few other dependencies and bumping some versions to make sure that its dependencies are compatible with whatever else we got).

As a next step we should remove the ledgerblue in _vendor directory and put it as a regular dependency in setup.py. Before we had to vendorize it because of a dependency collision with pycripto and pycriptodome but now they updated its dependencies so it's probably safe to upgrade everything.

**Comment by arturgontijo** [comment]
There is a "new way" to make this works with the new version of pycoin: [pycoin/pull/342#issuecomment](https://github.com/richardkiss/pycoin/pull/342#issuecomment-507453455)
